version: '3'

services:
  withdrawal-docker-compose-app-container:
    image: withdrawal-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/withdrawal-app
    ports:
      - "8091:8091"